### ISSUE TITLE
Advanced Scheduler

### ISSUE THREAD

**Issue by keeganryan** [keeganryan/AsbestOS#38]
Implement the Advanced scheduler:

See http://courses.cms.caltech.edu/cs124/pintos_9.html

TODO:
Calculating Priority: Done for all threads every fourth clock tick.
Calculating Recent CPU: Running thread's is incremented at each clock tick. All are recalculated every 1s.
Calculating Load Average: Done every 1s. There is one global value.
Fixed Point Real Arithmetic: See document.

**Comment by keeganryan** [comment]
Created new branch feature/hw3/advanced_scheduler and added files for fixed point arithmetic

**Comment by keeganryan** [comment]
What should be done: declare all necessary values in thread.h using float_fp construct. Then each of the TODOS can proceed semi-independently

**Comment by jaleng** [comment]
I'll work on fixed point

**Comment by keeganryan** [comment]
I'll add the fields to thread.h
