### ISSUE TITLE
System Calls

### ISSUE THREAD

**Issue by martinpablofabbri** [keeganryan/AsbestOS#48]
Should implement and test read/write in user virtual address space first
(needed for getting system code from user stack)

- [x] `void halt(void) NO_RETURN`
- [x] `void exit(int status) NO_RETURN`
- [x] `pid_t exec(const char *file)`
- [x] `int wait(pid_t)`
- [x] `bool create(const char *file, unsigned initial_size)`
- [x] `bool remove(const char *file)`
- [x] `int open(const char *file)`
- [x] `int filesize(int fd)`
- [x] `int read(int fd, void *buffer, unsigned length)`
- [x] `int write(int fd, const void *buffer, unsigned length)`
- [x] `void seek(int fd, unsigned position)`
- [x] `unsigned tell(int fd)`
- [x] `void close(int fd)`

numbers for syscalls defined in "`lib/syscall-nr.h`"

**Comment by martinpablofabbri** [comment]
B2: file descriptors and open files: unique within entire OS or just process?
B3: code for reading/writing user data from kernel
B4: worse/best-case of page table inspections for pull page copied from user space to kernel
B5: `wait` syscall implementation
B6: algorithms and design decisions for ending process of bad pointer-value and calls to error-handlers
B7: `exec` syscall synchronization
B8: race conditions on parent and child processes
B9: design justification for user memory access
B10: advantages/disadvantages for file descriptor design
B11: If `tid_t <-> pid_t` mapping was changed: what are advantages

**Comment by jaleng** [comment]
I'll work on create, remove, open, close.
