### ISSUE TITLE
Order Of Implementation

### ISSUE THREAD

**Issue by martinpablofabbri** [keeganryan/AsbestOS#50]
**INITIAL IMPLEMENTATION TO GET TESTS RUNNING/MINIMAL FUNCTIONALITY**
 - [x] argument passing
 - [x] user memory access (all read, few write)
 - [x] system call infrastructure (read syscall from stack -> dispatch to handler)
 - [x] exit syscall
 - [x] write (to fd 1 system console)
 - [x] initial implementation of process_wait() to infinite loop

**Comment by keeganryan** [comment]
Check out feature/hw4/minimal_implementation.
All of these are done to some extent. User reading is done, writing is not. Exit is not done correctly. Write is functional but incomplete

**Comment by keeganryan** [comment]
I'm working on argument passing now

**Comment by keeganryan** [comment]
Argument passing is done.
